baseURL = "https://dinwy.github.io/"
languageCode = "en-us"
title = "Dinwy's blog"
theme = "simpleD"
builddrafts = true
disablePathToLower = true

[params]
author = "Dinwy"
twitter = "https://twitter.com/Dinwy2016"
github = "https://github.com/Dinwy"
linkedIn = "https://www.linkedin.com/in/kyeong-jae-min-02aa66114/"
stackoverflow = "http://stackoverflow.com/users/5545216/dinwy"
summaryLength = 200
logoPath = "/img/logo.svg"