baseURL = "https://dinwy.github.io"
languageCode = "en-us"
title = "Dinwy's blog"
theme = "simpleD"
builddrafts = true
disablePathToLower = true

[params]
author = "Dinwy"
twitter = "https://twitter.com/Dinwy2016"
github = "https://github.com/Dinwy"
stackoverflow = "http://stackoverflow.com/users/5545216/dinwy"
summaryLength = 200